function openAll(){
    window.open("https://contexto.me/")
    window.open("https://www.nytimes.com/games/wordle/index.html")
    window.open("https://www.nytimes.com/games/connections")
    window.open("https://globle-game.com/")
    window.open("https://globle-capitals.com/")
    window.open("https://travle.earth/")
    window.open("https://actorle.com/")
    window.open("https://framed.wtf/")
    window.open("https://episode.wtf/")
    window.open("https://guessthe.game/")
    window.open("https://guesstheaudio.com/")
    window.open("https://metazooa.com")
    window.open("https://linxicon.com")         
    close()
}
